### ISSUE TITLE
LoadLibrary failed with error 126 

### ISSUE THREAD

**Issue by lvjurenbaba** [AUTOMATIC1111/stable-diffusion-webui-rembg#3]
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=1024x1536 at 0x250236FB370>, None, '', '', True, 0, 1, 512, 512, True, 'None', 'None', 0, 0, 0, 0, 'u2net', False, False, 240, 10, 10) {}
Traceback (most recent call last):
  File "E:\NEW_SD\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\NEW_SD\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\NEW_SD\stable-diffusion-webui\modules\postprocessing.py", line 56, in run_postprocessing
    scripts.scripts_postproc.run(pp, args)
  File "E:\NEW_SD\stable-diffusion-webui\modules\scripts_postprocessing.py", line 130, in run
    script.process(pp, **process_args)
  File "E:\NEW_SD\stable-diffusion-webui\extensions\stable-diffusion-webui-rembg\scripts\postprocessing_rembg.py", line 53, in process
    session=rembg.new_session(model),
  File "E:\NEW_SD\stable-diffusion-webui\venv\lib\site-packages\rembg\session_factory.py", line 66, in new_session
    ort.InferenceSession(
  File "E:\NEW_SD\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "E:\NEW_SD\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 408, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1106 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "E:\NEW_SD\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

After I downloaded the onnx i met this

**Comment by judy** [comment]
I got this too and was able to fix it by reading [this comment](https://github.com/danielgatis/rembg/issues/312#issuecomment-1465316591) on the rembg repo. In short:
1. You'll want to make sure you have the right versions of CUDA, cuDNN, and Nvidia TensorRT. I ended up installing all three of those. (The link says to use CUDA 11, but I needed CUDA 12.)
2. Once installed, make sure the paths to the folders containing those DLLs are on your PATH when running the interface. Instead of modifying my system environment variables, I changed my `webui-user.bat` file to change the PATH like this:

```
set PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin;C:\Program Files\Common Files\TensorRT-8.6.0.12\lib;%PATH%
```

Adjust that yourself based on what the folders are on your own system. TensorRT in particular came as a zip file and no installer, so I stuck it in `C:\Program Files\Common Files`. No idea if that's the ideal location for that sort of thing, so your mileage will vary!

**Comment by RafaRed** [comment]
It works. Thank you @judy

**Comment by CansecoDev** [comment]
Awesome it's working now, on my setup I went for:

- cuda 11.8
- cudnn 8.8.1.3 (for cuda 11)
- tensorrt 8.6.0.12 (for cuda11)

![old](https://user-images.githubusercontent.com/5104584/225495196-6ba3550a-981f-4fe3-ac73-1e8302399c91.jpg)
![00117](https://user-images.githubusercontent.com/5104584/225495260-0ac8e11d-7694-4214-b2d0-05ed21a894a5.png)

**Comment by lvjurenbaba** [comment]
@judy Appreciate,i download Tensort8.6 and set path as you, it finally works!
